file406: src/main/resources/ftpFiles/406/
file408: src/main/resources/ftpFiles/408/
file402: src/main/resources/ftpFiles/402/
file404: src/main/resources/ftpFiles/404/
file410: src/main/resources/ftpFiles/410/
file412: src/main/resources/ftpFiles/412/